### PR TITLE
Extended-Django-User-Class-39

### PR DESCRIPTION
**Pull request by Master-Minja**
Added Edipi using the AbstractUserModel from Django, added some functionality to the looking up on admin page, CHANGED CLASS User to Account, using 'Users' is very annoying due to django using similar naming conventions

Be advised ive made some migrations which might result in some conflicts,

### CODE REVIEW

**Comment by breencp** [comment]
Users table was renamed to mlpt_users to avoid conflicting with Django users.

**Comment by Master-Minja** [comment]
ok, so should i change the class from Account to Mlpt_Users, i can thats an easy fix, but not sure if its really necessary

**Comment by breencp** [comment]
Technically you could name it whatever you want, but we will want the Django models to mirror the underlying database schema.

**Comment by Master-Minja** [comment]
Class is now named Mlpt_Users

**Comment by purgat0ry** [comment]
This branch breaks the registration function. Reviewing still...

image

**Pull request merged**
